# Generated by Django 4.1.5 on 2023-01-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_fileupload_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
