# Generated by Django 4.1.5 on 2023-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(default='images/no_image.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
