# Generated by Django 4.1.5 on 2023-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
