# Generated by Django 4.1.5 on 2023-01-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
