# Generated by Django 4.1.5 on 2023-01-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_image_post_rename_img_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
